export const typeList1 = [
  { name: "不限", id: 0 },
  { name: "品牌故事", id: 1 },
  { name: "品牌故事", id: 2 },
  { name: "品牌故事", id: 3 },
  { name: "品牌故事", id: 4 },
  { name: "品牌故事", id: 5 },
  { name: "品牌故事", id: 6 },
  { name: "品牌故事", id: 7 },
  { name: "品牌故事", id: 8 },
  { name: "品牌故事", id: 9 },
];
export const typeList2 = [
  { name: "不限", id: 0 },
  { name: "打游戏", id: 1 },
  { name: "睡觉", id: 2 },
  { name: "吃饭", id: 3 },
  { name: "唱歌", id: 4 },
  { name: "泡妞", id: 5 },
  { name: "读书", id: 6 },
  { name: "考试", id: 7 },
  { name: "生娃", id: 8 },
  { name: "去世", id: 9 },
  { name: "重生", id: 10 },
  { name: "复活", id: 11 },
  { name: "再来一次", id: 12 },
  { name: "恭喜大家", id: 13 },
  { name: "考试", id: 14 },
  { name: "生娃", id: 15 },
  { name: "去世", id: 16 },
  { name: "重生", id: 17 },
  { name: "复活", id: 18 },
  { name: "再来一次", id: 19 },
  { name: "恭喜大家", id: 20 },
  { name: "恭喜大家", id: 21 },
];
